=== visualengineers/cobro-data/_schema/pattern.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://raw.githubusercontent.com/visualengineers/cobro-data/master/_schema/pattern.schema.json",
	"title": "Pattern",
	"description": "A pattern for constructionplans",
	"type": "object",
	"properties": {
		"id": {
			"description": "The unique identifier for a pattern",
			"type": "string"
		},
		"what": {
			"description": "Construction Blocks for the What Area",
			"type": "array",
			"items": {
				"type": "integer"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"why": {
			"description": "Construction Blocks for the Why Area",
			"type": "array",
			"items": {
				"type": "integer"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"how": {
			"description": "Construction Blocks for the How Area",
			"type": "array",
			"items": {
				"type": "integer"
			},
			"minItems": 1,
			"uniqueItems": true
		},
		"graphic":{
			"description": "if a graphic exists in the assets",
			"type":"boolean"
		}
	},
	"required": [ "id", "what", "why", "how" ]
}

=== visualengineers/cobro-data/_patterns/streetmap.json
{
    "id": "streetmap",
    "what": [
        1010301,
        1020101,
        1020201
    ],
    "why": [
        2020000,
        2030000
    ],
    "how": [
        3010101,
        3010302,
        3010304,
        3020101,
        3040501,
        3050102,
        3050105,
        3050205
    ]
}

=== visualengineers/cobro-data/_patterns/zoomable_facets_boxes.json
{
    "id": "zoomable_facets_boxes",
    "what": [
        1010101,
        1010102,
        1020101,
        1020201
    ],
    "why": [
        2020000,
        2030000
    ],
    "how": [
        3010305,
        3020101,
        3040301,
        3050205,
        3050209
    ],
    "graphic": true
}

=== visualengineers/cobro-data/_patterns/cluster_interactive_points.json
{
    "id": "cluster_interactive_points",
    "what": [
        1010500,
        1020101,
        1020202,
        1020201
    ],
    "why": [
        2030000
    ],
    "how": [
        3010301,
        3020401,
        3040305,
        3050106,
        3050202,
        3050207
    ],
    "graphic": true
}

=== visualengineers/cobro-data/_patterns/radial_bar_chart_stacked.json
{
    "id": "radial_bar_chart_stacked",
    "what": [
        1010104,
        1020101,
        1020202
    ],
    "why": [
        2010000,
        2020000,
        2030000
    ],
    "how": [
        3010101,
        3020201,
        3040301,
        3050204,
        3050209
    ],
    "graphic": true
}

=== visualengineers/cobro-data/_patterns/focus_area.json
{
    "id": "focus_area",
    "what": [
        1010500,
        1020101,
        1020201,
        1020202
    ],
    "why": [
        2010000,
        2020000,
        2030000
    ],
    "how": [
        3010303,
        3020201,
        3040305,
        3050106,
        3050204,
        3050203,
        3050206
    ],
    "graphic": true
}

=== visualengineers/cobro-data/_patterns/hierarchical_config_menu.json
{
    "id": "hierarchical_config_menu",
    "what": [
        1010101,
        1020101
    ],
    "why": [
        2010000,
        2020000,
        2030000
    ],
    "how": [
        3010305,
        3020201,
        3040303,
        3040604,
        3050202,
        3050104,
        3050205
    ],
    "graphic": true
}
